import { RULES, DEMO_DISCLAIMER, DEMO_DISCLAIMER_AR } from './rules.js';
import { loadSummary } from './calculations.js';
import { EXTRACTION_NOTICE } from './demo-adapter.js';

/** @param {unknown} value */
export function escapeHTML(value) {
  return String(value ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c] ?? c);
}
/** @param {import('./models').Assessment} assessment */
export function generateReport(assessment) {
  const a = assessment, h = escapeHTML;
  if (!a.drawing || !a.calculations.length || !['review', 'completed'].includes(a.stage)) throw new Error('No current analyzed assessment to report / لا يوجد تقييم محلل لإنشاء تقرير');
  const load = loadSummary(a.equipment);
  const pass = a.checks.filter(c => c.result === 'pass').length;
  const unresolved = a.findings.filter(f => f.decision !== 'resolved').length;
  const rules = RULES.filter(r => a.checks.some(c => c.ruleId === r.id));
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Maeyar AI — ${h(a.id)}</title><style>
  *{box-sizing:border-box}body{font-family:Arial,Tahoma,sans-serif;color:#15343e;line-height:1.65;max-width:1100px;margin:auto;padding:32px;background:white}h1,h2{color:#083b47}header{border-bottom:3px solid #149c91;padding-bottom:24px}small{color:#53717b}.ar{direction:rtl;text-align:right}.notice{background:#fff6df;border-inline-start:4px solid #b98b34;padding:15px;margin:16px 0}table{width:100%;border-collapse:collapse;font-size:12px;margin:18px 0}th,td{text-align:start;padding:9px;border:1px solid #cedde1;vertical-align:top;overflow-wrap:anywhere}th{background:#eef6f6}.finding{border:1px solid #ccdfe1;margin:18px 0;padding:18px;break-inside:avoid}code{white-space:normal;overflow-wrap:anywhere}.Critical{border-inline-start:4px solid #bc3e42}.Major{border-inline-start:4px solid #bc8a32}.meta{display:grid;grid-template-columns:1fr 1fr;gap:12px}.print{padding:10px;cursor:pointer}@media print{.print{display:none}body{padding:0}thead{display:table-header-group}h2{break-after:avoid}table{font-size:10px}}@media(max-width:600px){body{padding:15px}.meta{grid-template-columns:1fr}table{display:block;overflow:auto}}
  </style></head><body>
  <header><small>ENGINEERING DEVELOPMENT · AUTOMATED CODE AUDITING AND COMPLIANCE</small><h1>مِعيار AI | Maeyar AI</h1><h2>Electrical assessment report / تقرير التقييم الكهربائي</h2><p>AI interprets. Deterministic rules verify. The licensed engineer decides.</p><p class="ar">الذكاء الاصطناعي يفسّر، القواعد الحتمية تتحقق، والمهندس المرخّص يقرر.</p><p>${h(a.id)} · ${h(a.updatedAt)} · ${a.demo ? 'PRESENTATION ONLY / عرض تجريبي فقط' : 'LOCAL PILOT RECORD / سجل تجربة محلي'}</p></header>
  <button class="print" onclick="window.print()">Print / Save PDF — طباعة / حفظ PDF</button>
  <section><h2>Project & drawing information / بيانات المشروع والمخطط</h2><div class="meta">${Object.entries(a.project).map(([k, v]) => `<div><strong>${h(k)}</strong>: ${h(v)}</div>`).join('')}<div><strong>Drawing / المخطط</strong>: ${h(a.drawing.name)}</div><div><strong>File size / حجم الملف</strong>: ${h(a.drawing.size)} bytes</div></div></section>
  <div class="notice">${h(EXTRACTION_NOTICE)}<br>${h(DEMO_DISCLAIMER)}<br><span class="ar">${h(DEMO_DISCLAIMER_AR)}</span></div>
  <section><h2>Executive summary / الملخص التنفيذي</h2><p>${a.checks.length} check instances / فحص · ${pass} passed / مجتاز · ${a.findings.length} findings / ملاحظات · ${unresolved} not marked resolved / غير معالجة · ${a.findings.filter(f => f.decision === 'pending').length} pending decisions / قرارات معلقة.</p><p>Connected / الحمل المتصل: ${load.connectedKW} kW · Demand / حمل الطلب: ${load.demandKW.toFixed(2)} kW · Demo factor / عامل تجريبي: ${load.demandFactor}</p><p>Engineer decisions do not change deterministic pass/fail results. “Resolved” is a reviewer disposition, not proof that the drawing is compliant. / قرارات المهندس لا تغير نتائج القواعد؛ وصف «معالجة» لا يثبت مطابقة المخطط.</p></section>
  <section><h2>Assessment scope / نطاق التقييم</h2><p>Balanced three-phase current, connected/demand loads, nominal protection coordination, input-based cable ampacity, resistive voltage-drop approximation, metadata, earthing presence, rating completeness, label consistency and phase-load balance. Short-circuit withstand is NOT calculated; a validated study is required.</p><p class="ar">يشمل التقييم الأحمال والتيار وتنسيق الحماية وسعة الكابل التجريبية وهبوط الجهد التقريبي واكتمال البيانات والتأريض والتسميات وتوازن الأطوار. لا يحسب تحمل القصر ويلزم إعداد دراسة معتمدة.</p></section>
  <section><h2>Findings & evidence chain / الملاحظات وسلسلة الأدلة</h2>${a.findings.map(f => `<article class="finding ${h(f.severity)}"><h3>${h(f.severity)} · ${h(f.id)}</h3><strong>${h(f.title.en)}</strong><p class="ar">${h(f.title.ar)}</p><p>${h(f.location)} · ${h(f.equipmentId)} · Sample confidence / ثقة العينة: ${(f.confidence * 100).toFixed(0)}%</p><p><b>Drawing evidence / دليل المخطط:</b> ${h(f.evidence.drawing)}</p><p><b>Extracted value / القيمة:</b> ${h(f.extractedValue)}</p><p><b>Expected / المتطلب:</b> ${h(f.expectedRequirement)}</p><p><b>Calculation / الحساب:</b> <code>${h(f.calculation)}</code></p><p><b>Rule / القاعدة:</b> ${h(f.evidence.rule)}</p><p><b>Corrective action / الإجراء:</b> ${h(f.recommendedAction.en)}</p><p class="ar">${h(f.recommendedAction.ar)}</p><p><b>Engineer decision / قرار المهندس:</b> ${h(f.decision)} · ${h(f.reviewer)} · ${h(f.reviewedAt || 'Pending / معلق')}</p><p>${h(f.comment)}</p>${a.comments.filter(c => c.findingId === f.id).map(c => `<p><small>${h(c.reviewer)} · ${h(c.timestamp)}</small><br>${h(c.comment)}</p>`).join('')}</article>`).join('')}</section>
  <section><h2>Reproducible calculations / الحسابات القابلة لإعادة الإنتاج</h2><table><thead><tr><th>Equipment / المعدات</th><th>Design current / التيار</th><th>Voltage drop / هبوط الجهد</th><th>Corrected ampacity / السعة</th></tr></thead><tbody>${a.calculations.map(c => `<tr><td>${h(c.equipmentId)}</td><td>${h(c.formula)}</td><td>${h(c.voltageDropFormula)}</td><td>${c.correctedAmpacityA.toFixed(2)} A</td></tr><tr><td colspan="4">${h(c.assumptions)}</td></tr>`).join('')}</tbody></table></section>
  <section><h2>Rule references & governance / مراجع القواعد وحوكمتها</h2><table><thead><tr><th>ID / المعرف</th><th>Source / المصدر</th><th>Version / الإصدار</th><th>Clause / البند</th><th>Validation / التحقق</th></tr></thead><tbody>${rules.map(r => `<tr><td>${h(r.id)}</td><td>${h(r.source)} · ${h(r.edition)}</td><td>${h(r.version)}</td><td>${h(r.clause)}</td><td>${h(r.verificationStatus)}</td></tr>`).join('')}</tbody></table></section>
  <section><h2>Audit trail / سجل التدقيق</h2><table><thead><tr><th>Time / الوقت</th><th>Action / الإجراء</th><th>Actor / المستخدم</th><th>Detail / التفاصيل</th></tr></thead><tbody>${a.audit.map(e => `<tr><td>${h(e.timestamp)}</td><td>${h(e.action)}</td><td>${h(e.actor)}</td><td>${h(e.detail)}</td></tr>`).join('')}</tbody></table></section>
  <section><h2>Engineer sign-off / توقيع مراجعة المهندس</h2>${a.signoff ? `<p>${h(a.signoff.reviewer)} · License / الترخيص: ${h(a.signoff.license)} · ${h(a.signoff.timestamp)}</p><p>${h(a.signoff.comment)}</p><p>${h(a.signoff.statement)}</p>` : '<p>UNSIGNED — awaiting licensed-engineer review / غير موقع — بانتظار مراجعة المهندس المرخّص</p>'}</section>
  <section class="notice"><h2>Limitations & disclaimer / الحدود وإخلاء المسؤولية</h2><p>No live AI extraction, no licensed code text, no independently verified rule pack, no authenticated identity, no cryptographic signature, and no tamper-proof server audit storage. All uploaded formats use the same explicitly labeled sample model. Calculations omit reactance and installation-specific verification. Do not use this pilot as statutory design approval or as the sole basis for construction.</p><p class="ar">لا يوجد استخراج آلي حي أو نصوص أكواد مرخّصة أو حزمة قواعد معتمدة أو تحقق هوية أو توقيع رقمي موثق أو سجل خادم غير قابل للتلاعب. جميع الملفات تستخدم نموذج العينة نفسه بصورة معلنة. لا تستخدم هذه التجربة لاعتماد التصميم نظاميًا أو أساسًا وحيدًا للتنفيذ.</p></section>
  </body></html>`;
}

/** @param {import('./models').Assessment} assessment */
export function downloadReport(assessment) {
  const url = URL.createObjectURL(new Blob([generateReport(assessment)], { type: 'text/html;charset=utf-8' }));
  const anchor = document.createElement('a');
  anchor.href = url; anchor.download = `${assessment.id}-bilingual-report.html`; anchor.click();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}